### ISSUE TITLE
Running script in 2.4

### ISSUE THREAD

**Issue by rskallies** [jullrich/dshieldpfsense#3]
pfSense 2.4 was released. Unfortunately the script silently stopped working on 2.4

**Comment by jullrich** [comment]
just approved a patch to fix this hopefully.

**Comment by cjwaian** [comment]
Fix is working in pfSense 2.4.2-RELEASE-p1, the client version # was the same as my older script which was confusing but nevertheless success.

**Comment by rskallies** [comment]
Yes this fix is working on  pfSense 2.4.2-RELEASE-p1. The client version in the script is still the same as before the fix:  0.000003
