### ISSUE TITLE
Script fails on PFsense 2.4.4

### ISSUE THREAD

**Issue by gderf** [jullrich/dshieldpfsense#8]
I made the following changes required to get the script to run error free:

Replaced "split" with "preg_split" on lines 33 & 34:

$interfaces=preg_split(',',$config['interfaces']);
$authorized_source_ip=preg_split(',',$config['authorized_source_ip']);

However, when the script is run the pfsense System Log reports:

/root/bin/dshield.php: no new lines added to log since last run OK.....

Even though there are new rejected packets in the log. This is preventing email to be sent to dshield or any CC: address.

Additional question, please clarify the purpose of a new dshield.ini item:

#prevent auto ban ...
authorized_source_ip="172.16.0.60,10.0.0.100"

**Comment by oneoffdallas** [comment]
Hrm... You were right to remove split as it is removed in 7 and beyond. Looks like the preg_split on $config['interfaces'] isn't returning anything although the variable without preg_split does. If you only have one variable in your ini, you may be able to remove the preg_split altogether for the time being.

**Comment by nliaudat** [comment]
@gderf I added authorized_source_ip, cause if had many blocked packets in my logs emanating from remote vpn peers in my organisation. That caused to report my own as an offender ;( . 
The "authorized_source_ip" must be a public IP, not a private range as in sample

**Comment by oneoffdallas** [comment]
preg functions must have delimiters. Try the following lines instead.
$interfaces=preg_split('/,/',$config['interfaces']);
$authorized_source_ip=preg_split('/,/',$config['authorized_source_ip']);

**Comment by nliaudat** [comment]
I mean explode() can do the do job instead of split()

**Comment by oneoffdallas** [comment]
Agreed. Explode is the better option.
